version: '3.9'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.4-jammy
    restart: always
    container_name: usersdb
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
